package com.kieslingdev.mindscale.data

import androidx.room.Room
import androidx.sqlite.db.SimpleSQLiteQuery
import androidx.test.core.app.ApplicationProvider
import androidx.test.ext.junit.runners.AndroidJUnit4
import kotlinx.coroutines.runBlocking
import org.junit.After
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotEquals
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(AndroidJUnit4::class)
class MarkerDaoTest {

    private lateinit var database: MindScaleDatabase
    private lateinit var dao: MarkerDao

    @Before
    fun createDatabase() {
        val context = ApplicationProvider.getApplicationContext<android.content.Context>()
        database = Room.inMemoryDatabaseBuilder(context, MindScaleDatabase::class.java).build()
        dao = database.markerDao()
    }

    @After
    fun closeDatabase() {
        database.close()
    }

    @Test
    fun insert_persistsTsAndTextExactlyAsGiven() = runBlocking {
        val id = dao.insert(Marker(ts = 12_345L, text = "started sertraline 50mg"))

        // MarkerDao is intentionally read-free this phase (Marker rows are consumed by
        // the later Full log screen) — verify persistence via a raw query instead.
        val cursor = database.query(SimpleSQLiteQuery("SELECT ts, text FROM markers WHERE id = ?", arrayOf(id)))
        cursor.use {
            assertEquals(true, it.moveToFirst())
            assertEquals(12_345L, it.getLong(0))
            assertEquals("started sertraline 50mg", it.getString(1))
        }
    }

    @Test
    fun insert_assignsDistinctAutoGeneratedIds() = runBlocking {
        val firstId = dao.insert(Marker(ts = 1_000L, text = "dose change"))
        val secondId = dao.insert(Marker(ts = 2_000L, text = "started therapy"))

        assertNotEquals(firstId, secondId)
    }
}
